name: CICD

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t treelancer/pratham-vite-app .
      - name: Publish image to docker hub
        run: docker push treelancer/pratham-vite-app:latest   

  deploy-main: 
    needs: build
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Pull image from docker hub
        run: docker pull treelancer/pratham-vite-app:latest 
      - name: Delete Old Container
        run: docker rm -f reactContainer
      - name: Run docker container
        run: docker run -d -p 3000:80 --name reactContainer treelancer/pratham-vite-app

  deploy-dev: 
    needs: build
    runs-on: self-hosted
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Pull image from docker hub
        run: docker pull treelancer/pratham-vite-app:latest 
      - name: Delete Old Container
        run: docker rm -f reactContainerDev
      - name: Run docker container for dev
        run: docker run -d -p 3001:80 --name reactContainerDev -e VITE_NAME="Utkarsh Kushwaha dev" -e VITE_USER="dev.mitmeerut@gmail.com" treelancer/pratham-vite-app
